### ISSUE TITLE
Compilation fails with NDEBUG enabled

### ISSUE THREAD

**Issue by kbabioch** [Yubico/libfido2#8]
With version 0.3.0 I'm encountering issues during compilation when trying to compile the software with NDEBUG and the following flags:

	/usr/bin/cmake /home/abuild/rpmbuild/BUILD/libfido2-0.3.0/. '-GUnix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 -DCMAKE_BUILD_TYPE=RelWithDebInfo '-DCMAKE_C_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG' '-DCMAKE_CXX_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG' '-DCMAKE_Fortran_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG' '-DCMAKE_EXE_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DCMAKE_MODULE_LINKER_FLAGS=-Wl,--as-needed '-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DLIB_SUFFIX=64 -DCMAKE_SKIP_RPATH:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF -DCMAKE_COLOR_MAKEFILE:BOOL=OFF -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_MODULES_INSTALL_DIR=/usr/share/cmake/Modules -DCMAKE_INSTALL_PREFIX=/usr -DCBOR_LIBRARY_DIRS=/usr/lib64

There are multiple warnings regarding unused variables / parameters:

	[   18s] cd /home/abuild/rpmbuild/BUILD/libfido2-0.3.0/build/regress && /usr/bin/cc -DHAVE_ENDIAN_H -DHAVE_ERR_H -DHAVE_EXPLICIT_BZERO -DHAVE_GETOPT -DHAVE_GETPAGESIZE -DHAVE_SYSCONF -DHAVE_UNISTD_H -D_FIDO_MAJOR=0 -D_FIDO_MINOR=3 -D_FIDO_PATCH=0 -D_GNU_SOURCE -I/home/abuild/rpmbuild/BUILD/libfido2-0.3.0/src -I/usr/include/hidapi  -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -Wall -Wextra -Werror -Wshadow -Wwrite-strings -Wmissing-prototypes -Wbad-function-cast -pedantic -pedantic-errors -fstack-protector-all -std=c99 -Wno-unused-result -Wcast-qual -O2 -g -DNDEBUG -fPIE   -o CMakeFiles/regress_assert.dir/assert.c.o   -c /home/abuild/rpmbuild/BUILD/libfido2-0.3.0/regress/assert.c
	[   18s] /home/abuild/rpmbuild/BUILD/libfido2-0.3.0/regress/assert.c: In function 'dummy_close':
	[   18s] /home/abuild/rpmbuild/BUILD/libfido2-0.3.0/regress/assert.c:65:19: error: unused parameter 'handle' [-Werror=unused-parameter]
	[   18s]  dummy_close(void *handle)
	[   18s]              ~~~~~~^~~~~~
	[   18s] /home/abuild/rpmbuild/BUILD/libfido2-0.3.0/regress/assert.c: In function 'empty_assert':
	[   18s] /home/abuild/rpmbuild/BUILD/libfido2-0.3.0/regress/assert.c:166:44: error: unused parameter 'a' [-Werror=unused-parameter]
	[   18s]  empty_assert(fido_dev_t *d, fido_assert_t *a, int idx)
	[   18s]                              ~~~~~~~~~~~~~~~^
	[   18s] /home/abuild/rpmbuild/BUILD/libfido2-0.3.0/regress/assert.c:166:51: error: unused parameter 'idx' [-Werror=unused-parameter]
	[   18s]  empty_assert(fido_dev_t *d, fido_assert_t *a, int idx)
	[   18s]                                                ~~~~^~~
	[   18s] /home/abuild/rpmbuild/BUILD/libfido2-0.3.0/regress/assert.c: In function 'empty_assert_tests':
	[   18s] /home/abuild/rpmbuild/BUILD/libfido2-0.3.0/regress/assert.c:219:16: error: variable 'io_f' set but not used [-Werror=unused-but-set-variable]
	[   18s]   fido_dev_io_t io_f;
	[   18s]                 ^~~~
	[   18s] At top level:
	[   18s] /home/abuild/rpmbuild/BUILD/libfido2-0.3.0/regress/assert.c:15:28: error: 'es256_pk' defined but not used [-Werror=unused-const-variable=]
	[   18s]  static const unsigned char es256_pk[64] = {
	[   18s]                             ^~~~~~~~
	[   18s] cc1: all warnings being treated as errors

It seems that this version (in particular the regress module) has not been compiled with `NDEBUG` defined. This is appended to the build flags automaticalyl in our build system, which is not unusual for production releases.

**Comment by kbabioch** [comment]
This boils down to `regress/assert.c` using a lot of assert statements, which are removed when compiling with NDEBUG, so the compiler complains about those unused parameters / variables.

For instance:

	empty_assert(fido_dev_t *d, fido_assert_t *a, int idx)
	{
		    es256_pk_t *es256;
		    rs256_pk_t *rs256;

		    assert(fido_assert_flags(a, idx) == 0);
		    assert(fido_assert_authdata_len(a, idx) == 0);
		    assert(fido_assert_authdata_ptr(a, idx) == NULL);
		    assert(fido_assert_clientdata_hash_len(a) == 0);
		    assert(fido_assert_clientdata_hash_ptr(a) == NULL);
		    assert(fido_assert_id_len(a, idx) == 0);
		    assert(fido_assert_id_ptr(a, idx) == NULL);
		    assert(fido_assert_rp_id(a) == NULL);
		    assert(fido_assert_sig_len(a, idx) == 0);
		    assert(fido_assert_sig_ptr(a, idx) == NULL);
		    assert(fido_assert_user_display_name(a, idx) == NULL);
		    assert(fido_assert_user_icon(a, idx) == NULL);
		    assert(fido_assert_user_id_len(a, idx) == 0);
		    assert(fido_assert_user_id_ptr(a, idx) == NULL);
		    assert(fido_assert_user_name(a, idx) == NULL);

**Comment by martelletto** [comment]
Thank you for the report.

It seems to me that the best way to go is to skip the regression 
tests (by not building them) if NDEBUG is defined.  Does that sound 
reasonable to you?

-p.

**Comment by kbabioch** [comment]
Yes, makes sense to me, but I'm mostly just a user of this library, not exactly sure what these regression tests are doing and whether they would be useful in production.

**Comment by martelletto** [comment]
I have pushed a fix to distinguish between debug/release builds 
depending on the value of CMAKE_BUILD_TYPE. Regression tests are 
then skipped unless CMAKE_BUILD_TYPE is "Debug".

Thank you again for your report.

-p.

**Comment by kbabioch** [comment]
Thanks for the fast fix. Unfortunately this does not seem to fix it for me. I still get the same mistakes as initially reported. cmake is invoked in the following way:

	/usr/bin/cmake /home/abuild/rpmbuild/BUILD/libfido2-0.3.0/. '-GUnix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 -DCMAKE_BUILD_TYPE=RelWithDebInfo '-DCMAKE_C_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG' '-DCMAKE_CXX_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG' '-DCMAKE_Fortran_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG' '-DCMAKE_EXE_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DCMAKE_MODULE_LINKER_FLAGS=-Wl,--as-needed '-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DLIB_SUFFIX=64 -DCMAKE_SKIP_RPATH:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF -DCMAKE_COLOR_MAKEFILE:BOOL=OFF -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_MODULES_INSTALL_DIR=/usr/share/cmake/Modules -DCMAKE_INSTALL_PREFIX=/usr -DCBOR_LIBRARY_DIRS=/usr/lib64 -DCMAKE_BUILD_TYPE=Release

**Comment by kbabioch** [comment]
Forget about my last comment, it works just fine. The patch wasn't applied correctly before.

**Comment by martelletto** [comment]
Ok, I will then close the issue. Thank you.

-p.
